"""phase1 initial schema

Revision ID: 1e31f3f4b909
Revises: 
Create Date: 2026-06-26 19:09:44.418635
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1e31f3f4b909'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evaluation_ranges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_key', sa.String(length=40), nullable=False),
    sa.Column('range_order', sa.SmallInteger(), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'indicator_key', 'range_order', name='uq_eval_user_indicator_order')
    )
    op.create_index('ix_eval_user_indicator', 'evaluation_ranges', ['user_id', 'indicator_key'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), sa.Computed('CASE WHEN ended_at IS NULL THEN NULL ELSE FLOOR(EXTRACT(EPOCH FROM (ended_at - started_at)) / 60) END', persisted=True), nullable=True),
    sa.Column('average_tables', sa.SmallInteger(), nullable=True),
    sa.Column('concentration_level', sa.SmallInteger(), nullable=True),
    sa.Column('emotional_state', sa.Enum('excellent', 'good', 'neutral', 'tired', 'tilt', 'frustrated', 'distracted', name='ck_session_emotional_state', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('concentration_level IS NULL OR concentration_level BETWEEN 1 AND 5', name='ck_session_concentration'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_session_time_order'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('tags',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('theme', sa.String(length=20), server_default=sa.text("'dark'"), nullable=False),
    sa.Column('default_table_size', sa.SmallInteger(), server_default=sa.text('9'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tournaments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('poker_room', sa.String(length=100), nullable=False),
    sa.Column('tournament_name', sa.String(length=255), nullable=True),
    sa.Column('game_type', sa.Enum('holdem', 'omaha', 'omaha_hilo', 'stud', name='ck_tour_game_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('betting_structure', sa.Enum('nl', 'pl', 'fl', name='ck_tour_betting_structure', native_enum=False, create_constraint=True, length=4), nullable=False),
    sa.Column('speed', sa.Enum('regular', 'turbo', 'hyper', 'deep', name='ck_tour_speed', native_enum=False, create_constraint=True, length=10), server_default=sa.text("'regular'"), nullable=False),
    sa.Column('entry_structure', sa.Enum('freezeout', 'rebuy', 'reentry', 'satellite', 'shootout', name='ck_tour_entry_structure', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('bounty_type', sa.Enum('none', 'knockout', 'progressive', 'mystery', name='ck_tour_bounty_type', native_enum=False, create_constraint=True, length=12), server_default=sa.text("'none'"), nullable=False),
    sa.Column('table_size', sa.SmallInteger(), server_default=sa.text('9'), nullable=False),
    sa.Column('final_table_size', sa.SmallInteger(), server_default=sa.text('9'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=18, scale=8), server_default=sa.text('1.0'), nullable=False),
    sa.Column('buy_in', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('addon_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('guarantee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('prize', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('rebuys', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('reentries', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('add_ons', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('entrants', sa.Integer(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), sa.Computed('buy_in * (1 + rebuys + reentries) + addon_cost', persisted=True), nullable=False),
    sa.Column('profit_native', sa.Numeric(precision=14, scale=2), sa.Computed('prize - (buy_in * (1 + rebuys + reentries) + addon_cost)', persisted=True), nullable=False),
    sa.Column('profit_base', sa.Numeric(precision=16, scale=2), sa.Computed('(prize - (buy_in * (1 + rebuys + reentries) + addon_cost)) * fx_rate_to_base', persisted=True), nullable=False),
    sa.Column('itm', sa.Boolean(), sa.Computed('prize > 0', persisted=True), nullable=False),
    sa.Column('winner', sa.Boolean(), sa.Computed('final_position = 1', persisted=True), nullable=False),
    sa.Column('final_table', sa.Boolean(), sa.Computed('final_position <= final_table_size', persisted=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('buy_in >= 0', name='ck_tour_buyin_nonneg'),
    sa.CheckConstraint('entrants >= 1', name='ck_tour_entrants'),
    sa.CheckConstraint('final_position >= 1', name='ck_tour_position'),
    sa.CheckConstraint('fx_rate_to_base > 0', name='ck_tour_fx_positive'),
    sa.CheckConstraint('prize >= 0', name='ck_tour_prize_nonneg'),
    sa.CheckConstraint('rebuys >= 0 AND reentries >= 0 AND add_ons >= 0', name='ck_tour_counts_nonneg'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tournaments_order', 'tournaments', ['user_id', 'date', 'start_time', 'id'], unique=False)
    op.create_index('ix_tournaments_user_profit', 'tournaments', ['user_id', 'profit_base'], unique=False)
    op.create_index('ix_tournaments_user_room', 'tournaments', ['user_id', 'poker_room'], unique=False)
    op.create_table('hand_reviews',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_tags',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_tags')
    op.drop_table('hand_reviews')
    op.drop_index('ix_tournaments_user_room', table_name='tournaments')
    op.drop_index('ix_tournaments_user_profit', table_name='tournaments')
    op.drop_index('ix_tournaments_order', table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_table('user_settings')
    op.drop_table('tags')
    op.drop_index('ix_sessions_user_started', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_eval_user_indicator', table_name='evaluation_ranges')
    op.drop_table('evaluation_ranges')
    op.drop_table('users')
    # ### end Alembic commands ###
